[package]
name = "rts"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
wasmtime = "13.0.0"
wasmtime-wasi = "13.0.0"

[lib]
name = "asm_x86_64"
path = "src/lib/asm_x86_64.rs"

[[bin]]
name = "rts"
path = "src/main.rs"

